In [1]:
import numpy as np
rows = int(input("Enter number of rows: "))
columns = int(input("Enter number of columns: "))
print("Enter elements of first matrix:")
matrix1 = []
for i in range(rows):
    row = []
    for j in range(columns):
        row.append(int(input()))
    matrix1.append(row)
print("Enter elements of second matrix:")
matrix2 = []
for i in range(rows):
    row = []
    for j in range(columns):
        row.append(int(input()))
    matrix2.append(row)
matrix1 = np.array(matrix1)
matrix2 = np.array(matrix2)
result = matrix1 + matrix2
print("First Matrix:")
print(matrix1)
print("Second Matrix:")
print(matrix2)
print("Addition of Two Matrices:")
print(result)

Enter number of rows:  2
Enter number of columns:  2


Enter elements of first matrix:


 1
 2
 3
 4


Enter elements of second matrix:


 1
 2
 3
 4


First Matrix:
[[1 2]
 [3 4]]
Second Matrix:
[[1 2]
 [3 4]]
Addition of Two Matrices:
[[2 4]
 [6 8]]
